### ISSUE TITLE
Application doesn't show images

### ISSUE THREAD

**Issue by Hund** [bubelov/news#125]
It doesn't show images for me in the articles.

Example website that I've tried:

Website: https://ndanes.com
Web feed: https://ndanes.com/feed.xml

I'm using version 0.3.2 from F-Droid with the Miniflux backend on my Google Pixel 3a with LineageOS.

**Comment by frogtile** [comment]
It shows images on an article from a different feed.

Feed: https://drewdevault.com/blog/index.xml

https://drewdevault.com/2021/12/30/Language-design-considerations.html

But not on a post, first one, I have tried on the mentioned feed.

**Comment by bubelov** [comment]
@Hund regarding ndanes.com

The app currently relies on this callback when fetching images:

https://developer.android.com/reference/android/text/Html.ImageGetter#getDrawable(java.lang.String)

> This method is called when the HTML parser encounters an img tag. The source argument is the string from the "src" attribute; the return value should be a Drawable representation of the image or null for a generic replacement image. Make sure you call setBounds() on your Drawable if it doesn't already have its bounds set.

I assumed that it should always return absolute URLs, but that doesn't seem to be the case. This website uses relative paths for img tags, which is rather uncommon but valid, according to RSS validator.

Since Android's HTML parser doesn't have enough data to construct absolute URL, image fetching function fails. The app has this data, so this issue should be easily fixable.

**Comment by bubelov** [comment]
Fixed in https://github.com/bubelov/news/commit/36e2bcad3850c0ed8b34e65c43b1a43d45fe37b4
