### ISSUE TITLE
Google News RSS feed shows duplicates

### ISSUE THREAD

**Issue by slodown** [bubelov/news#134]
Hi,
I'm using the Google News RSS ain Standalone Mode.
When I do a manual update fetch some feeds are shown twice or triple.
Would be nice to add a feture to remote those dupicates.
Thanky you!

**Comment by bubelov** [comment]
@slodown did you download it from Google Play?

**Comment by slodown** [comment]
No I'm using the one from F-Droid, didn't know there is an Google Play version...

**Comment by slodown** [comment]
https://news.google.com/rss?hl=de&gl=DE&ceid=DE:de

**Comment by bubelov** [comment]
@slodown Google Play version was banned so it's better not to use it anyway. Google wants app developers to be able to censor content which is not compatible with many feed readers, including this one

**Comment by bubelov** [comment]
@slodown disregard the previous message, I can see duplicates now

**Comment by bubelov** [comment]
It's not that simple, this feed is really odd...

First, it assigns an integer `guid` to it's stories, like:

```xml
<title>
Russia pushes war in Ukraine close to U.S. NATO allies' border with airstrikes near Poland as talks continue - CBS News
</title>
<guid isPermaLink="false">1333000611</guid>
```

Then, it magically becomes a string:

```xml
<title>
Russia pushes war in Ukraine close to U.S. NATO allies' border with airstrikes near Poland as talks continue - CBS News
</title>
<guid isPermaLink="false">
CAIiEPGlgb2A8k_SNFmNjAEI61UqGQgEKhAIACoHCAowyNj6CjDyiPICMJyFxQU
</guid>
```

It's the same story with the same title, but Google changes it's `id` every minute. This `id` is supposed to be constant, because every `id` is interpreted as a separate news item. I'm not sure if there are good ways to fix this in the app, this feed seems to be completely broken. Do you know any feed reader apps which don't show duplicates for this feed?

**Comment by slodown** [comment]
Thanks for your troubleshooting and review.

The "inoreader" app should have a feature which can handle this, bt it was not working for google news.

I'm using now miniflux, before that i used nextcloud. I hoped to manage with those tools, but no success.

I also tried atom feed: https://news.google.com/atom?hl=de&gl=DE&ceid=DE:de (same :( thing here)

**Comment by bubelov** [comment]
Closing because this feed breaks the Atom spec, there is nothing the app can reliably do to fix it
