### ISSUE TITLE
Nextcloud single sign-on doesn't work on Android 11

### ISSUE THREAD

**Issue by eyand** [bubelov/news#16]
I have Nextcloud installed via F-droid, but I'm prompted to install it from the Play Store before I can use the app.

**Comment by bubelov** [comment]
Can be due to #5

**Comment by p-fruck** [comment]
Hi, are there any updates on this? As far as I can tell, the changes have been merged into the master branch of nextcloud/Android-SingleSignOn back in May and other apps like Nextcloud Notes are working just fine. I would really appreciate working SSO within this app, since it is so much more convenient. Thank you in advance

**Comment by bubelov** [comment]
@p-fruck I saw a few RC builds in their feed, looks like they're in a feature freeze/bug fixing stage now. It's just a guess but I would expect a release pretty soon

Other apps might work because they choose to target obsolete Android API in order to work around this issue

**Comment by bubelov** [comment]
@p-fruck I just tried updating this dep, although it's still RC, and it seems to be working. If you want to grab the latest version from the unreleased master branch, the APK is available here: https://github.com/bubelov/news/actions

**Comment by p-fruck** [comment]
Awesome, just installed it and it works like charm. Much more convenient than manually configuring the nextcloud credentials :smile: Thank you for your time and work!
