### ISSUE TITLE
Fetching stuck and keep loop requesting `/v1/feeds`

### ISSUE THREAD

**Issue by ckt1031** [bubelov/news#214]
### Checklist

- [x] I am using the latest version 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

Connect miniflux with latest version

### Actual behavior

It keeps stuck at loading and looping requests

### Screenshots/Screen recordings

![image](https://github.com/bubelov/news/assets/65409152/b44f9868-724c-4712-84b4-bd88a31e122b)
![image](https://github.com/bubelov/news/assets/65409152/c6759dd4-8a01-4d13-a761-b99ad5032ba7)

### Device info

 - Android version/Custom ROM version: 12
 - Device model: Xiaomi

**Comment by blacklight** [comment]
I can confirm this issue. The app used to work fine for me, until 2-3 days ago it suddenly started experiencing the same problem - requests get stuck in a loop on /api/v1/feeds.

Since this issue was open months ago and got no answer (and the same applies to many other issues), is it fair to ask if the project is still actually maintained? If it's not then I'm ok to fork it and look into fixing what's broken for me at least.

**Comment by bubelov** [comment]
The project is indeed maintained, I'm using it every day and everything works like a charm. Of course you can fork it, or just submit a pull request. I rarely look at the issues since this project collected ~$14 in maintenance donations, so I moved on to more in-demand open source projects.

**Comment by blacklight** [comment]
@bubelov the error is now reproducible on any instance of the app I have installed on my devices when I connect to my Miniflux instance - but any other client works fine.

I've done a bit of debugging and it seems that things fail [in `FeedsRepo.sync` on `api.getFeeds()`](https://github.com/bubelov/news/blob/master/app/src/main/kotlin/feeds/FeedsRepo.kt#L80) - the underlying error is `Invalid URL host: ""`.

The app doesn't process errors in the `sync` block properly and it gets stuck in a loop instead of reporting the error and exiting (and that's probably part of the problem too, as it ends up doing ~10 requests/sec to my server).

Not sure where that empty host comes from. My hypotheses (both to validate):

1. The instance URL isn't saved/loaded properly
2. Some feeds in the returned list have invalid/empty URLs, thus breaking the whole get process.

If you have some insights on what may be causing it, it'd save me a bit of debugging time.

**Comment by blacklight** [comment]
More debugging: I've found the culprit. It was a specific feed on my server - namely this one: `https://thmsmlr.com/rss`.

Reason:

```
❯ curl -s 'https://thmsmlr.com/rss' | head -6
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
  <channel>
    <title>The Thoughts of @thmsmlr</title>
    <description>As the title suggests</description>
    <link>https:///</link>
```

Note the `<link>https:///</link>` line.

This break things [here](https://github.com/bubelov/news/blob/master/app/src/main/kotlin/api/miniflux/MinifluxApiAdapter.kt#L146) when the app tries to build the `alternateLink` for the feed using `site_url` - parsing that URL obviously breaks, and without anything in the stack that can handle the exception the error bubbles up all the way to the top level, resulting in the `sync` task being called forever.

IMHO if some feeds in my list are invalid, I shouldn't be expected to spin up an Android Studio session, build the app and debug it to understand which one it is.

- (Obvious) solution 1: I can just remove that feed from my list and the app will work fine.
- (Better) solution 2: The app should implement better error handling. If the alternate link of a feed is broken, that probably shouldn't break the whole feed object. And if the feed has more serious issues that prevent the construction of the object altogether (e.g. the feed is just an empty string or the XML is broken), then the app should probably just exclude that feed from the list and move on (and, ideally, maybe show a little toast message to the user to inform them about the broken feed). In no case `FeedRepo.sync` should break with an unhandled exception and get stuck in a fetch loop without notifying the user.

If you want I can put put together a PR with *solution 2*.

**Comment by blacklight** [comment]
PR ready: https://github.com/bubelov/news/pull/222

**Comment by bubelov** [comment]
1. Yes, this feed does not validate, according to https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fthmsmlr.com%2Frss

2. The current error handling in incomplete and any improvements are welcome, let me check that PR
