### ISSUE TITLE
Layout options

### ISSUE THREAD

**Issue by Donkey-Doug** [bubelov/news#27]
Make it possible to customize the layout. For example,

- Image on the left or right.
- Large card-style centered image with the headline either above or below the image.
- Large card-style centered image with the headline on top of the image. Add shadow around white text to remain readable.
- Change padding around images. Let the user choose vertical and horizontal padding. Make it possible for content to reach the sides of the screen (0 horizontal padding) and completely eliminate the space between articles (0 vertical padding).
- Two or more columns of articles. Particularly useful for landscape mode.
- Hide/show the source.
- Show/hide preview text.

**Comment by bubelov** [comment]
Some of those suggestions will be implemented eventually, but I can't tell which ones yet. In the next release, users will be able to hide preview images per-feed (#63). I personally interested in this change and I'll use it so it makes sense to add it. Adding more exotic options and combining them is tricky because no one will test and maintain all those combinations (I won't even know if something is broken so it will be a constant source of problems for me and the rest of the users).
