### ISSUE TITLE
Atom feeds

### ISSUE THREAD

**Issue by fossdd** [bubelov/news#31]
I've tried to add the following feed: https://gitlab.com/fdroid/rfp/-/issues.atom?feed_token=gdoyU2ZstimRyxzcCh4P&state=opened

On new install, add the feed. Go to News page and refresh. Message comes: `Expected URL scheme: 'http' or 'https' but no colon found`. Go to feed section and `Open feed` crashes the app without a warning or so.

Other feeds like https://f-droid.org/feed.xml does work.

Not sure if it's happing cause this type of RSS feeds don't work. Or if GitLab (host of the feed) had something changed, what the app doesn't like.

I'm using the standalone version without Nextcloud integration.

Thanks in Advance. Your App really look good!

**Comment by bubelov** [comment]
@fossdd it looks like this feed has a relative self-link:

```xml
<link 
  href="/fdroid/rfp/-/issues.atom?feed_token=gdoyU2ZstimRyxzcCh4P&amp;state=opened" 
  rel="self" 
  type="application/atom+xml"/>
```

It's unusual and makes parsing harder. I've modified the parser to ignore this tag if it doesn't have a protocol prefix. Instead, it will opt to user-provided URL.

Here is the patched version: 

https://cloud.bubelov.com/s/nWASpmJpWBdYPfc

It will also be fixed in the next release. Please note that current F-Droid release is in fact an ancient version of this app, I have no idea why it stopped fetching new releases, maybe they have some internal issues which cause this lag.

Also, I wouldn't recommend to add too many feeds in standalone mode. It is completely untested and unoptimized. It will likely fail to update your feeds even if a single one of them goes offline. I'm planning to fix it in future but it's very fragile at the moment.

**Comment by fossdd** [comment]
Oh okay, 

F-Droid had some bugs in the build system. The versions `0.2.6` was all detected. But they sren't builded yet.

My NC account has A LOT of feeds, I have to clean up.. So the standalone mode was only "for testing".

Anyway, thanks for fixing!

**Comment by bubelov** [comment]
@fossdd yes, standalone mode is still incomplete. 

I've noticed that your feed URL has a token in it. I hope it's not private token with sensitive permissions, otherwise you should probably nuke it ASAP.

**Comment by fossdd** [comment]
Yes, there aren't any private informations. But for private issues in GitLab. Anyway I revoked and reseted the token. Thanks. :P


20 Feb 2021, 10:05 by notifications@github.com:
