### ISSUE TITLE
Crash on import from OPML

### ISSUE THREAD

**Issue by Donkey-Doug** [bubelov/news#33]
The app crashes when I try to import an OPML file. There is no exception log.

Version: 0.2.6

**Comment by bubelov** [comment]
@Donkey-Doug could you provide that OPML file? Did it happen in standalone or NC mode?

**Comment by Donkey-Doug** [comment]
Standalone mode.

OPML:

**Comment by bubelov** [comment]
@Donkey-Doug my parser assumed that some optional fields should be present. This feed is "minimalistic" but valid so I relaxed those requirements. Fixed in https://github.com/bubelov/news/commit/6f8be56c3b8bd7cf5525e9f8106789ae479665eb.

PS. By the way, standalone mode should be usable since the next release. By usable, I mean it won't fail to update feeds if any of those feeds is currently offline which was a big problem for users with lots of feeds.
