### ISSUE TITLE
Delete entries older than ...

### ISSUE THREAD

**Issue by Donkey-Doug** [bubelov/news#34]
Add an option to delete entries older than a certain amount of time. For example, delete all entries older than 1 day.

**Comment by bubelov** [comment]
@Donkey-Doug can you expand on what you are trying to achieve? Read entries are hidden by default and one of the new features in 0.2.7 is the ability to mark all of the items you scrolled in your news feed as read, automatically. Would it solve your issue or you're concerned about old news taking up your storage or something else?

**Comment by Donkey-Doug** [comment]
Most news readers have such funcionality. It ensures there is no old content in my news reader. For example, if a user does not read the news on sunday, then he sees many items when he or she tries to read the news on monday.

The "mark when scrolled" feature is very welcome though.

**Comment by zynexiz** [comment]
This function is mentioned [here](https://github.com/bubelov/news/issues/3#issuecomment-773268609), not sure if @bubelov implemented in the same commit to?

**Comment by bubelov** [comment]
@zynexiz no, the app never deletes news, it's the job of Nextcloud back end. You can configure cache purging policy in Nextcloud settings. You can also configure it to keep news forever, as I do. I like the ability to search all of my news by a keyword in order to find all the relevant articles when a certain topic pops up in a conversation and in other situations when I need to find stuff that I read long time ago.

The problem here is that different people use the app differently. I have a carefully picked set of personal blogs in my feeds and I don't use the app every day. Missing some articles is not an option. On the other hand, some people may use News app for, well, literally, reading news. The content of many news sites is ephemeral and it quickly becomes irrelevant so I can understand the desire to delete the "old news" automatically.

**Comment by zynexiz** [comment]
@bubelov Ah, missed the "delete" part here, mine was merely for marking the article as read, not deleting the article. As you said, that's the servers job :) As far as I know, the official app don't delete anything either, just marks it as read. Personally, I use the app for actually reading the news. As I mentioned before, have quite a lot so I don't read them all.

**Comment by bubelov** [comment]
Implemented in https://github.com/bubelov/news/commit/ac6c8165804c0b2fa6862a6f938987940f34fb79
