### ISSUE TITLE
Hide opened news + mark scrolled as read bug

### ISSUE THREAD

**Issue by Donkey-Doug** [bubelov/news#38]
Version: 0.2.7
Mode: Standalone mode

The function hide opened news fails in combination with mark scrolled as read. The news is marked as read, but still shown even though "hide opened news"-view is active. 

In order to hide the entries, a refresh is needed.

**Comment by bubelov** [comment]
@Donkey-Doug it's intentional. The app won't delete any feed items automatically because it creates a lot of crazy scrolling problems. That's how I did it, initially, and it worked pretty terrible. Android list widget is not optimized for handling a stream of remove requests while scrolling. You have to reload the content or just leave the screen in order to trigger the filter.
