### ISSUE TITLE
Can't login with Nextcloud on Android 11

### ISSUE THREAD

**Issue by citizenserious** [bubelov/news#5]
Without GApps, with only the Nextcloud app from F-Droid there is no way to sign in. Error: Nextcloud Files App is not installed.
Login over the Files App works in the offical App for example. 
It worked for me on Android 10 with OpenGApps

Nextcloud Files App 3.14.1
News: 0.2.2
Android 11

**Comment by bubelov** [comment]
@citizenserious thanks for reporting this issue! 

I don't think it has anything to do with Google because this app doesn't depend on Google services, but it could be related to https://github.com/nextcloud/Android-SingleSignOn/issues/277. This issue will be resolved sooner or later.

In the meantime, I'll enable "manual" login in the next release. It's not as convenient but it should make the app less fragile.

**Comment by bubelov** [comment]
@citizenserious I've included the manual login option in the latest release. It will probably take a few days to propagate to F-Droid. You can also install a dev APK and check if your issue has been resolved: https://github.com/bubelov/news/releases/tag/v0.2.3. Dev builds don't conflict with the release builds from F-Droid, so you can have both and use the dev build while waiting for the update.

**Comment by citizenserious** [comment]
@bubelov Wow, thank you very much for the fast reply and workaround, the manual login works perfect (: Keep up the great work.
