### ISSUE TITLE
Some feeds don't work

### ISSUE THREAD

**Issue by Farzat07** [bubelov/news#65]
[This feed](https://lukesmith.xyz/rss.xml) works on [feeder app](https://gitlab.com/spacecowboy/Feeder) but not on this app (no entries shown).

Using the standalone setting.

**Comment by bubelov** [comment]
@Farzat07 I'll take a look on that feed, and there is probably something wrong with my parser. Note that the feed itself is also non-conforming to RSS spec. I'm not sure how severe are those issues, but if you're in contact with that guy, maybe you can let him know:

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Flukesmith.xyz%2Frss.xml

**Comment by bubelov** [comment]
@Farzat07 OK, I see what happens. All of the dates in this feed have leading space, so it looks like " Sat, 13 Mar 2021 08:47:51 -0500" instead of "Sat, 13 Mar 2021 08:47:51 -0500", which pisses off date parser. I can probably trim spaces from both sides without breaking other feeds and it should do the trick.

**Comment by bubelov** [comment]
Fixed in latest release
